# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b0b72c7c97db3a253e2b8ae214c935aac3dca29cf3fd97bf7b6e50d8af206d13788590543a6e4bb4699373dcd2e7b5463078aae542c35bc94549a1ff59299efc

test:
  secret_key_base: b076efd63f61cd8de8e10ec7b630399e1e2c5c3abe301688c4be0e065ab745332c787b25b0e1f6ced16956c433f78ed55dd0057abe7b462e56c5814567b50594

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
